
/* - AMX Mod Include -------------------------------------------- *

 *  UTIL_amx_only
 *  (c) Copyright 2003-2004, Created by Ryan.
 *
 *  A collection of useful functions that are used in the war3x
 *  plugin source for the AMX version only. These functions are
 *  stock in the AMXX version.
 *
 *
 *  Enjoy!

 * -------------------------------------------------------------- */


// Found in AMXX <engine>

stock is_valid_ent( ent ) { return is_entity( ent ); }